/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AppClass.sm
 */


#import "statemap.h"

// Forward declarations.
@class Map1;
@class Map1_Start;
@class Map1_Zeros;
@class Map1_Ones;
@class Map1_OK;
@class Map1_Error;
@class Map1_Default;
@class AppClassState;
@class AppClassContext;
@protocol AppClass;

@interface AppClassState : SMCState
{
}
- (void)Entry:(AppClassContext*)context;
- (void)Exit:(AppClassContext*)context;

- (void)EOS:(AppClassContext*)context;
- (void)One:(AppClassContext*)context;
- (void)Unknown:(AppClassContext*)context;
- (void)Zero:(AppClassContext*)context;

- (void)Default:(AppClassContext*)context;
@end

@interface Map1 : NSObject
{
}
+ (Map1_Start*)Start;
+ (Map1_Zeros*)Zeros;
+ (Map1_Ones*)Ones;
+ (Map1_OK*)OK;
+ (Map1_Error*)Error;
@end

@interface Map1_Default : AppClassState
{
}
@end

@interface Map1_Start : Map1_Default
{
}
- (void)EOS:(AppClassContext*)context;
- (void)One:(AppClassContext*)context;
- (void)Unknown:(AppClassContext*)context;
- (void)Zero:(AppClassContext*)context;
@end

@interface Map1_Zeros : Map1_Default
{
}
- (void)EOS:(AppClassContext*)context;
- (void)One:(AppClassContext*)context;
- (void)Unknown:(AppClassContext*)context;
- (void)Zero:(AppClassContext*)context;
@end

@interface Map1_Ones : Map1_Default
{
}
- (void)EOS:(AppClassContext*)context;
- (void)One:(AppClassContext*)context;
- (void)Unknown:(AppClassContext*)context;
- (void)Zero:(AppClassContext*)context;
@end

@interface Map1_OK : Map1_Default
{
}
@end

@interface Map1_Error : Map1_Default
{
}
- (void)EOS:(AppClassContext*)context;
- (void)One:(AppClassContext*)context;
- (void)Unknown:(AppClassContext*)context;
- (void)Zero:(AppClassContext*)context;
@end

@interface AppClassContext : SMCFSMContext
{
    __weak id<AppClass> _owner;
}
- (id)initWithOwner:(id<AppClass>)owner;
- (id)initWithOwner:(id<AppClass>)owner state:(SMCState*)aState;
- (id<AppClass>)owner;
- (AppClassState*)state;

- (void)enterStartState;

- (void)EOS;
- (void)One;
- (void)Unknown;
- (void)Zero;
@end


/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
